# ============================================================== #
# Language Configuration Section                                 #
# ============================================================== #

language: "en" # Supported languages -> hu, en, es, fr, it, pl, pt

# ============================================================== #
# Command Settings                                               #
# ============================================================== #

aliases:
  - "grindstone"
  - "gs"

# ============================================================== #
# Menu Settings                                                  #
# ============================================================== #

grindstone:
  title: "&bGrindstone" # The title in the menu
  filler-glass-item:
    material: BLACK_STAINED_GLASS_PANE
    amount: 1
    name: " "
    lore:
      - " "
  enchantment-book-item:
    material: ENCHANTED_BOOK
    name: "&bEnchantments"
    amount: 1
    lore:
      - ""
      - "&aAvailable enchantments"
      - ""
  click-sound: BLOCK_NOTE_BLOCK_BELL # This sound will play on every click action in the menu
  before-symbol: "• " # This is the symbol which indicates the enchantment you at
  after-symbol: " » " # This is the symbol which indicates the level you select
  selected-enchantment-color: "&a"
  unselected-enchantment-color: "&7"
  price-xp-per-level: 1 # This is the cost of the use per level so if you take off unbreaking 2 it will deduct 2 xp because 2 * 1 = 2